# chapter2_core_concepts/outputs.tf

# This output will display information about the file created by the 'local_file'
# resource defined in main.tf.
output "generated_file_info" {
  description = "Information about the file generated by Terraform in this chapter, including its name and the input content prefix."
  value = {
    filename            = local_file.core_example.filename
    content_prefix_used = var.file_content_prefix
    content_version     = var.content_version_number
    # Note: The 'local_file' resource does not directly expose the length of its content as an attribute.
    # If we wanted to output the length of the generated content, we'd typically use a data source
    # to read the file after it's created, or use a built-in function like length() on the content variable itself.
    # For this example, we'll keep it simple and output the variables we used.
  }
  # To make it more sensitive, you could mark it as sensitive = true
  # sensitive = true
}

# Another example: Outputting the raw content if it's not sensitive.
# For this example, we assume the content is not sensitive.
output "generated_file_content_for_review" {
  description = "The full content written to the example file. Be cautious with outputting potentially sensitive content."
  value       = local_file.core_example.content # This directly references the content attribute of the resource.
}

# Note: Outputs are useful for:
# 1. Displaying values to the user after `terraform apply`.
# 2. Passing data to other Terraform configurations (root module outputs can become data sources for other modules).
# 3. Triggering actions in CI/CD pipelines based on output values.
